name: Trigger event to sync
description: Raise an `main_updated` event on the forked repo.

branding:
  icon: radio
  color: yellow

inputs:
  forked_repository_owner:
    description: 'Owner of the forked repository'
    required: true
  forked_repository_name:
    description: 'Name of the forked repository'
    required: true
  forked_repository_token:
    description: 'Personal Access Token of the forked repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Dispatch Event"
      run: |
          curl -X POST \
          -H "Authorization: token ${{ forked_repository_token }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/${{ forked_repository_owner }}/${{ forked_repository_name }}/dispatches" \
          -d '{"event_type": "main_updated"}'
